"""empty message

Revision ID: 2b72fcca1cee
Revises: c27f7d66cf8c
Create Date: 2017-08-08 00:10:01.294832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b72fcca1cee'
down_revision = 'c27f7d66cf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('point', sa.Integer(), nullable=True))
    op.drop_column(u'users', 'addition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('addition', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column(u'users', 'point')
    op.drop_table('recodes')
    # ### end Alembic commands ###
