"""empty message

Revision ID: 33625ee04ccb
Revises: 2b72fcca1cee
Create Date: 2017-08-12 14:08:19.537429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33625ee04ccb'
down_revision = '2b72fcca1cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bettinglist', sa.Column('check', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bettinglist', 'check')
    # ### end Alembic commands ###
